version: '3.8'

networks:
  ingress:
    external: true
    name: traefik-public

volumes:
  filebrowser_data:
  apache:


services:
  apache:
    image: "litespeedtech/openlitespeed:latest"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 100M
      replicas: 1
      placement:
        constraints:
          - node.labels.static == production
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${NAME}-static-http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-static-http.entrypoints=http
        - traefik.http.routers.${NAME}-static-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-static-https.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-static-https.entrypoints=https
        - traefik.http.routers.${NAME}-static-https.tls=true
        - traefik.http.routers.${NAME}-static-https.tls.certresolver=le
        - traefik.http.services.${NAME}-static.loadbalancer.server.port=${WEB_SERVER_PORT-80}
    volumes:
      - litespeed:/var/www/vhosts/localhost/html
    networks:
      - ingress
      
  filebrowser:
    image: hurlenko/filebrowser
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.static == production
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${NAME}-filebrowser-http.rule=Host(`cloud.saia.ar`) && PathPrefix(`/${NAME}`)
        - traefik.http.routers.${NAME}-filebrowser-http.entrypoints=http
        - traefik.http.routers.${NAME}-filebrowser-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-filebrowser-https.rule=Host(`cloud.saia.ar`) && PathPrefix(`/${NAME}`)
        - traefik.http.routers.${NAME}-filebrowser-https.entrypoints=https
        - traefik.http.routers.${NAME}-filebrowser-https.tls=true
        - traefik.http.routers.${NAME}-filebrowser-https.tls.certresolver=le
        - traefik.http.services.${NAME}-filebrowser.loadbalancer.server.port=${FB_PORT-8080}
    environment:
      FB_BASEURL: "/${NAME}/"
    volumes:
      - litespeed:/data/
      - filebrowser_data:/config
    networks:
      - ingress   
  


    
