# Static Stack
# OLS Version

version: '3.8'

networks:
  ingress:
    external: true
    name: ${INGRESS_NET}

volumes:
  filebrowser_data:
  litespeed:


services:
  litespeed:
    image: ${LITESPEED_IMAGE}
    deploy:
      resources:
        limits:
          cpus: ${LITESPEED_CPU_LIMIT}
          memory: ${LITESPEED_MEMORY_LIMIT}
      replicas: ${LITESPEED_REPLICAS}
      placement:
        constraints:
          - node.labels.static.${NODE_LABEL} == 1
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=${INGRESS_NET}
        - traefik.constraint-label=${INGRESS_NET}
        - traefik.http.routers.${NAME}-static-http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-static-http.entrypoints=http
        - traefik.http.routers.${NAME}-static-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-static-https.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-static-https.entrypoints=https
        - traefik.http.routers.${NAME}-static-https.tls=true
        - traefik.http.routers.${NAME}-static-https.tls.certresolver=le
        - traefik.http.services.${NAME}-static.loadbalancer.server.port=${WEB_SERVER_PORT-80}
    volumes:
      - litespeed:/var/www/vhosts/localhost/html
    networks:
      - ingress
      
  filebrowser:
    image: ${FB_IMAGE}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.static == production
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=${INGRESS_NET}
        - traefik.constraint-label=${INGRESS_NET}
        - traefik.http.routers.${NAME}-filebrowser-http.rule=Host(`${DRIVE_DOMAIN}`) && PathPrefix(`/${NAME}`)
        - traefik.http.routers.${NAME}-filebrowser-http.entrypoints=http
        - traefik.http.routers.${NAME}-filebrowser-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-filebrowser-https.rule=Host(`${DRIVE_DOMAIN}`) && PathPrefix(`/${NAME}`)
        - traefik.http.routers.${NAME}-filebrowser-https.entrypoints=https
        - traefik.http.routers.${NAME}-filebrowser-https.tls=true
        - traefik.http.routers.${NAME}-filebrowser-https.tls.certresolver=le
        - traefik.http.services.${NAME}-filebrowser.loadbalancer.server.port=${FB_PORT-8080}
    environment:
      FB_BASEURL: "/${NAME}/"
    volumes:
      - litespeed:/data/
      - filebrowser_data:/config
    networks:
      - ingress   
  


    
